vich_uploader:
  db_driver: orm # or mongodb, propel, etc.

  mappings:
    ressource_images:
      uri_prefix: /uploads/ressource_images
      upload_destination: "%kernel.project_dir%/public/uploads/ressources"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
